### ISSUE TITLE
Styles do not apply

### ISSUE THREAD

**Issue by scoricov** [pzi/middleman-basis#1]
After completing all steps from the "Getting Started" section, one can see the following:
![sample page middleman basis 2015-04-17 19-33-41](https://cloud.githubusercontent.com/assets/318745/7206334/04339b0a-e539-11e4-914f-e75a640a6715.jpg)
Ruby 2.1.2p95

**Comment by pzi** [comment]
Hi @scoricov,

There are no styles in this template other than the styles that are coming from [Normalize.css](https://github.com/necolas/normalize.css/). And by the looks of it, they are getting loaded properly. Otherwise your page would look like on the below screenshot:

![screen shot 2015-04-20 at 09 02 41](https://cloud.githubusercontent.com/assets/2037851/7222230/321134a6-e73c-11e4-8b8c-478a3871e5bb.png)

Middleman-basis doesn't come with an out of the box theme, that's part of the reason why it is called "basis". Everything is up to you.

Does this "resolve" your issue?

Cheers
Patrik

**Comment by scoricov** [comment]
Hi, Patrik
Thank you for your explanation, the idea has become clear to me now. Please close.

**Comment by pzi** [comment]
No problem, Alexey. Thanks for using my template!
